---
language: ruby
rvm:
- 1.9
- 2.0
- 2.1
- 2.2
- 2.3
- 2.4
- 2.5
- 2.6
- 2.7
before_install: ruby prepare_rubygems.rb
script: bundle exec rspec spec
gemfile:
- gemfiles/4.0.13.gemfile
- gemfiles/5.2.3.gemfile
- gemfiles/5.1.7.gemfile
- gemfiles/3.2.22.5.gemfile
- gemfiles/4.1.16.gemfile
- gemfiles/4.2.11.1.gemfile
- gemfiles/6.0.0.gemfile
- gemfiles/5.0.7.2.gemfile
matrix:
  exclude:
  - rvm: 1.9
    gemfile: gemfiles/6.0.0.gemfile
  - rvm: 1.9
    gemfile: gemfiles/5.2.3.gemfile
  - rvm: 1.9
    gemfile: gemfiles/5.1.7.gemfile
  - rvm: 1.9
    gemfile: gemfiles/5.0.7.2.gemfile
  - rvm: 1.9
    gemfile: gemfiles/4.2.11.1.gemfile
  - rvm: 1.9
    gemfile: gemfiles/4.1.16.gemfile
  - rvm: 1.9
    gemfile: gemfiles/4.0.13.gemfile
  - rvm: 2.0
    gemfile: gemfiles/6.0.0.gemfile
  - rvm: 2.0
    gemfile: gemfiles/5.2.3.gemfile
  - rvm: 2.0
    gemfile: gemfiles/5.1.7.gemfile
  - rvm: 2.0
    gemfile: gemfiles/5.0.7.2.gemfile
  - rvm: 2.1
    gemfile: gemfiles/6.0.0.gemfile
  - rvm: 2.1
    gemfile: gemfiles/5.2.3.gemfile
  - rvm: 2.1
    gemfile: gemfiles/5.1.7.gemfile
  - rvm: 2.1
    gemfile: gemfiles/5.0.7.2.gemfile
  - rvm: 2.2
    gemfile: gemfiles/6.0.0.gemfile
  - rvm: 2.2
    gemfile: gemfiles/5.2.3.gemfile
  - rvm: 2.2
    gemfile: gemfiles/5.1.7.gemfile
  - rvm: 2.2
    gemfile: gemfiles/5.0.7.2.gemfile
  - rvm: 2.3
    gemfile: gemfiles/6.0.0.gemfile
  - rvm: 2.4
    gemfile: gemfiles/6.0.0.gemfile
  - rvm: 2.4
    gemfile: gemfiles/4.1.16.gemfile
  - rvm: 2.4
    gemfile: gemfiles/4.0.13.gemfile
  - rvm: 2.4
    gemfile: gemfiles/3.2.22.5.gemfile
  - rvm: 2.5
    gemfile: gemfiles/4.1.16.gemfile
  - rvm: 2.5
    gemfile: gemfiles/4.0.13.gemfile
  - rvm: 2.5
    gemfile: gemfiles/3.2.22.5.gemfile
  - rvm: 2.6
    gemfile: gemfiles/4.1.16.gemfile
  - rvm: 2.6
    gemfile: gemfiles/4.0.13.gemfile
  - rvm: 2.6
    gemfile: gemfiles/3.2.22.5.gemfile
  - rvm: 2.7
    gemfile: gemfiles/4.2.11.1.gemfile
  - rvm: 2.7
    gemfile: gemfiles/4.1.16.gemfile
  - rvm: 2.7
    gemfile: gemfiles/4.0.13.gemfile
  - rvm: 2.7
    gemfile: gemfiles/3.2.22.5.gemfile
